### ISSUE TITLE
OKular flatpak is still can not utilizing printers though they appearing in printer list !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#79]
Hi. Just few hrs ago, I upgraded my Fedora 30 to 32 from within tty terminal in very smooth way & without any errors ...

Now I'm on flatpak version 1.6.3 For that Okular should, now, be able too print. But it is still not able to printing though all printers appearing in printer list !! Please see the following screenshots:

![1](https://user-images.githubusercontent.com/25375330/83323544-1cf29f00-a24f-11ea-8398-cf527ebd82d8.png)

![2](https://user-images.githubusercontent.com/25375330/83323547-22e88000-a24f-11ea-84cf-0565fc65a5fb.png)

My printer working very well ! I tried many programs installed on my system as .rpm packages from repositories & all worked to me to print without any error !

This issue should be already fixed - see last comments in the following closed issue:
https://github.com/flathub/org.kde.okular/issues/25

Kindly to fix this annoying issue !

**Comment by Erick555** [comment]
I can confirm this in Kubuntu 20.04. It seems that app needs `lpr` binary thus bundling cups.

**Comment by grulja** [comment]
Okular unfortunately doesn't use Qt printing system and uses directly CUPS binaries to print. These binaries seem not to be present in the runtime. Maybe we will need to bundle CUPS with Okular. @tsdgeos what do you think?

Hmm, I thought I tested printing with Okular and it worked before.

**Comment by Nokia808** [comment]
@grulja 
@tsdgeos 
Hi dears. If you like to bundle CUPS with Okular, do not forget to file an issue request for run time upstream to fix this issue so that when they fix it you can dis-bundle CUPS from this flatpak again. Is this better for flatpak project as a whole as I think ?

**Comment by Erick555** [comment]
@Nokia808 folks you just pinged ARE upstream.

**Comment by tsdgeos** [comment]
cups is part of the freedesktop-sdk but they only build the library not the binaries, never have.

I'd kind of prefer if they built lpr with cups and not us building it again, seems like building cups a second time is kind of asking for trouble.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1048

**Comment by Erick555** [comment]
What kind of trouble? To me it seems safe unless okular hardcodes paths to `/usr/bin` (which should be fixed there then). Bundling it with app seems more reasonable for me.

**Comment by tsdgeos** [comment]
Should be fixed now

**Comment by Nokia808** [comment]
@tsdgeos 
Hi. Yes it is working now ! Thank you very much ! But there is still other issue remain: "Print View" not working ! I will open new issue. However, you (all of you) did very good ! And I'm happy that I participated in improving this flatpak package by bug reports !
